# Generated by Django 5.2.5 on 2025-08-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_remove_enviowhatsapp_paciente_enviowhatsapp_carnet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviowhatsapp',
            name='carnet',
            field=models.CharField(max_length=20),
        ),
    ]
