# Generated by Django 5.2.6 on 2025-09-26 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaIdFechaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('inexistente', 'ID Inexistente'), ('sin_objetos', 'Sin citas'), ('invalido', 'ID Inválido'), ('error_conexion', 'Error de conexión')], max_length=20)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('identificador', models.CharField(max_length=20)),
                ('fecha_especificada', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsappIdFechaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('numero_destino', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('archivo_pdf', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido')], max_length=20)),
                ('detalle_error', models.TextField(blank=True, null=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('identificador', models.CharField(max_length=20)),
                ('fecha_especificada', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaFechaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('inexistente', 'ID Inexistente'), ('sin_objetos', 'Sin citas'), ('invalido', 'ID Inválido'), ('error_conexion', 'Error de conexión')], max_length=20)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_especificada', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsappFechaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('numero_destino', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('archivo_pdf', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido')], max_length=20)),
                ('detalle_error', models.TextField(blank=True, null=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_especificada', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CitasCarnetConsulta',
            fields=[
                ('consultaidfechabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosco.consultaidfechabase')),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosco.consultaidfechabase',),
        ),
        migrations.CreateModel(
            name='CitasColaboradorConsulta',
            fields=[
                ('consultaidfechabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosco.consultaidfechabase')),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosco.consultaidfechabase',),
        ),
        migrations.CreateModel(
            name='CitasCarnetWhatsapp',
            fields=[
                ('whatsappidfechabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosco.whatsappidfechabase')),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosco.whatsappidfechabase',),
        ),
        migrations.CreateModel(
            name='CitasColaboradorWhatsapp',
            fields=[
                ('whatsappidfechabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosco.whatsappidfechabase')),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosco.whatsappidfechabase',),
        ),
        migrations.CreateModel(
            name='EspaciosVaciosConsulta',
            fields=[
                ('consultafechabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosco.consultafechabase')),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosco.consultafechabase',),
        ),
        migrations.CreateModel(
            name='EspaciosVaciosWhatsapp',
            fields=[
                ('whatsappfechabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosco.whatsappfechabase')),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosco.whatsappfechabase',),
        ),
    ]
