# Generated by Django 5.2.7 on 2025-10-07 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappIdFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('numero_destino', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('archivo_pdf', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido')], max_length=20)),
                ('detalle_error', models.TextField(blank=True, null=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('identificador', models.CharField(max_length=20)),
                ('fecha_especificada', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaIdFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('inexistente', 'ID Inexistente'), ('sin_objetos', 'Sin citas'), ('invalido', 'ID Inválido'), ('error_conexion', 'Error de conexión')], max_length=20)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('identificador', models.CharField(max_length=20)),
                ('fecha_especificada', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('inexistente', 'ID Inexistente'), ('sin_objetos', 'Sin citas'), ('invalido', 'ID Inválido'), ('error_conexion', 'Error de conexión')], max_length=20)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_especificada', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsappFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('numero_destino', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('archivo_pdf', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido')], max_length=20)),
                ('detalle_error', models.TextField(blank=True, null=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_especificada', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CitasCarnetWA',
            fields=[
                ('whatsappidfecha_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosco.whatsappidfecha')),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosco.whatsappidfecha',),
        ),
        migrations.CreateModel(
            name='CitasColaboradorWA',
            fields=[
                ('whatsappidfecha_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosco.whatsappidfecha')),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosco.whatsappidfecha',),
        ),
        migrations.CreateModel(
            name='CitasColaborador',
            fields=[
                ('consultaidfecha_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosco.consultaidfecha')),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosco.consultaidfecha',),
        ),
        migrations.CreateModel(
            name='CitasPaciente',
            fields=[
                ('consultaidfecha_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosco.consultaidfecha')),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosco.consultaidfecha',),
        ),
        migrations.CreateModel(
            name='EspaciosVacios',
            fields=[
                ('consultafecha_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosco.consultafecha')),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosco.consultafecha',),
        ),
        migrations.CreateModel(
            name='EspaciosVaciosWA',
            fields=[
                ('whatsappfecha_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosco.whatsappfecha')),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosco.whatsappfecha',),
        ),
    ]
