# Generated by Django 5.2.6 on 2025-09-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitasCarnetConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('fecha_especificada', models.DateField(blank=True, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('inexistente', 'ID Inexistente'), ('sin_objetos', 'Sin citas'), ('invalido', 'ID Inválido'), ('error_conexion', 'Error de conexión')], max_length=20)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CitasCarnetWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('fecha_especificada', models.DateField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('numero_destino', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('archivo_pdf', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido')], max_length=20)),
                ('detalle_error', models.TextField(blank=True, null=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CitasColaboradorConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('fecha_especificada', models.DateField(blank=True, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('inexistente', 'ID Inexistente'), ('sin_objetos', 'Sin citas'), ('invalido', 'ID Inválido'), ('error_conexion', 'Error de conexión')], max_length=20)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CitasColaboradorWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('fecha_especificada', models.DateField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('numero_destino', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('archivo_pdf', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido')], max_length=20)),
                ('detalle_error', models.TextField(blank=True, null=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
