# Generated by Django 5.2.4 on 2025-08-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosco", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carnet", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("edad", models.IntegerField()),
                ("diagnostico", models.TextField()),
                ("grado", models.CharField(max_length=50)),
                ("fecha_ingreso", models.DateField()),
            ],
        ),
    ]
