# Generated by Django 5.2.4 on 2025-08-05 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosco", "0002_paciente"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvioWhatsApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_destino", models.CharField(max_length=20)),
                ("mensaje", models.TextField()),
                ("archivo_pdf", models.CharField(max_length=255)),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("enviado", "Enviado"), ("fallido", "Fallido")],
                        max_length=20,
                    ),
                ),
                ("detalle_error", models.TextField(blank=True, null=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kiosco.paciente",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MensajeWhatsApp",
        ),
    ]
