# Generated by Django 5.2.5 on 2025-08-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosco', '0006_citasconsulta_citaswhatsapp_delete_enviowhatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitasCarnetConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('fecha_especificada', models.DateField(blank=True, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CitasCarnetWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('numero_destino', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('archivo_pdf', models.CharField(max_length=255)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido')], max_length=20)),
                ('detalle_error', models.TextField(blank=True, null=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CitasColaboradorConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('fecha_especificada', models.DateField(blank=True, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CitasColaboradorWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('numero_destino', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('archivo_pdf', models.CharField(max_length=255)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido')], max_length=20)),
                ('detalle_error', models.TextField(blank=True, null=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CitasConsulta',
        ),
        migrations.DeleteModel(
            name='CitasWhatsapp',
        ),
    ]
