# Generated by Django 5.2.7 on 2025-11-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, max_length=50)),
                ('identificador', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_especificada', models.DateField(blank=True, db_index=True, null=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
